### ISSUE TITLE
Remove binary from the repository

### ISSUE THREAD

**Issue by winningsix** [intel-hadoop/chimera#22]
Currently so file is included in the repository. Need to ignore it.

**Comment by vanzin** [comment]
Thanks! Later on, I'd suggest an approach where each native library is built in a separate maven module (e.g. "chimera-lin32", "chimera-lin64", "chimera-win32", etc) so that they can be controlled using profiles; and then have a module that just packages all other native lib modules + the main java code into the final deliverable jar to be published.

That should allow a proper build system where each native library can be built separately.

**Comment by winningsix** [comment]
@vanzin Thank you for your suggestion. Now the makefile can do the cross platform compile work by certain ant target.(e.g. "```make win32```", "```make win64```". etc). If no arguments are specified, it will use ```OSInfo.Java``` to detect the OS info and Arch info and then generate the native library for that platform. In case you are able to and wanna compile cross platform, for example you are able to compile the native code for Win64 while you are in the Ubuntu (For cross-compilation Win64 on Ubuntu, install the g++-mingw-w64-x86-64 package). I have added the profiles to make sure users are able to compile the native by specifing the platform in profile in #36. This will not need to add more submodules in maven.
